# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
julia:
  - 1.4

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - wget -qO- https://bootstrap.pypa.io/get-pip.py | python

install:
  - python3 -m pip install qsosed

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

#jobs:
#  allow_failures:
#    - julia: nightly
#  fast_finish: true
#  include:
#    - stage: Documentation
#      julia: 1.4
#      script: julia --project=docs -e '
#          using Pkg;
#          Pkg.develop(PackageSpec(path=pwd()));
#          Pkg.instantiate();
#          include("docs/make.jl");'
#      after_success: skip
