# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

dist: bionic

julia:
  - 1.4

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7

before_install:
  - sudo apt-get update
  - sudo apt purge python2.7-minimal
  - sudo apt-get install python3 python3-pip python3-setuptools
  - pip3 install --upgrade pip
  - pip install qsosed

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

#jobs:
#  allow_failures:
#    - julia: nightly
#  fast_finish: true
#  include:
#    - stage: Documentation
#      julia: 1.4
#      script: julia --project=docs -e '
#          using Pkg;
#          Pkg.develop(PackageSpec(path=pwd()));
#          Pkg.instantiate();
#          include("docs/make.jl");'
#      after_success: skip
