# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.4
env:
  - CODECOV_TOKEN="ae04cd54-e81f-496c-aa77-ef280b59ab0e"

notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - CODECOV_TOKEN="ae04cd54-e81f-496c-aa77-ef280b59ab0e" julia -e 'using Pkg; using Coverage; Codecov.submit_local(process_folder())'
  #- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

codecov: true

#jobs:
#  allow_failures:
#    - julia: nightly
#  fast_finish: true
#  include:
#    - stage: Documentation
#      julia: 1.4
#      script: julia --project=docs -e '
#          using Pkg;
#          Pkg.develop(PackageSpec(path=pwd()));
#          Pkg.instantiate();
#          include("docs/make.jl");'
#      after_success: skip
