name = "Qwind"
uuid = "988db7c6-b368-4d8d-9ee1-ae26d5771fb3"
authors = ["Arnau Quera-Bofarull"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
docs = []
