system:
  qwind_path: /cosma/home/dp004/dc-quer1/Qwind.jl
  #qwind_path: /home/arnau/code/Qwind.jl
  n_cpus: 64
  partition: cosma6
  account: dp004
  max_time: 72:00:00
  job_name: qwind
  
black_hole:
  #M: "@vary grid 1e6,1e7,1e8,1e9,1e10" # solar masses
  M: 1e7
  #mdot: "@vary grid 0.025,0.05,0.075,0.1,0.25,0.5" # Eddington units
  mdot: 0.05
  spin: 0.0 # spin parameter (-1,1)

radiation:
  mode: QsosedRadiation # RERadiation: Risaliti & Elvis, QsosedRadiation: Done
  relativistic: true
  f_x: 0.15
  n_r: 2000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0
  xray_opacity: boost
  disk_integral_rtol: 1e-3


radiative_transfer:
  mode: RegularGrid
  interpolator: 
    type: WindInterpolator #"@vary grid VIGrid,WindInterpolator"
    vacuum_density: 1e2
    n_timesteps: 10000
    nz: 500 #"@vary grid 50,100,500,1000"
    nr: auto

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000.0
  z_min: 0.0
  z_max: 10000.0

initial_conditions:
  mode: CAKIC 
  r_in: 20.0
  r_fi: 1500.0
  n_lines: auto 
  log_spaced: true
  z_0: 0.0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.68

integrator:
  n_iterations: 50
  atol: 1e-8
  rtol: 1e-3
  save_path: "/cosma6/data/dp004/dc-quer1/qwind_runs/bh_scan_model7_ext"
  #save_path: "/cosma5/data/durham/covid19/arnau/qwind/bh_scan_model7_ext"
  #save_path: "/cosma7/data/dp004/dc-quer1/qwind_runs/bh_1e8"
  #save_path: "/home/arnau/code/Qwind.jl/bh_scan"
