system:
  qwind_path: /cosma/home/dp004/dc-quer1/Qwind.jl
  sysimage_path: /cosma/home/dp004/dc-quer1/sys_everywhere.so
  n_cpus: 16
  partition: cosma
  account: durham
  max_time: 72:00:00
  job_name: rin20 
  
black_hole:
  M: 1e6 #"@vary grid 1e6,1e7,1e8,1e9,1e10" 
  mdot: "@vary log 0.05 0.5 10"
  spin: 0.0 

radiation:
  relativistic: true
  f_uv: auto
  f_x: 0.15
  n_r: 2000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0
  xray_opacity: boost
  tau_uv_calculation: no_tau_uv #disk
  wind_interpolator:
    vacuum_density: 1e2
    n_integrator_interpolation: 10000
    nz: 500 
    nr: auto 

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000.0
  z_min: 0.0
  z_max: 10000.0

initial_conditions:
  mode: CAKIC 
  r_in: 20.0
  r_fi: 1500.0
  n_lines: auto 
  log_spaced: true
  z0: 0.0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.61
  use_precalculated: false

integrator:
  n_iterations: 50
  atol: 1e-8
  rtol: 1e-3
  save_path: "/cosma5/data/durham/covid19/arnau/qwind/final/moremdot/bh_scan_rin20_1e6"
  #save_path: "/cosma6/data/dp004/dc-quer1/qwind_runs/bh_scan_rin20_ext"
