black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  relativistic: true
  f_uv: auto
  f_x: 0.15
  n_r: 1000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0
  uv_opacity: thomson
  xray_opacity: boost 
  xray_scattering: true
  tau_uv_calculation: no_tau_uv
  vacuum_density: 1e2
  update_grid_method: "average"
  grid_nz: 500
  grid_nr: auto

initial_conditions:
  mode: cak
  r_in: 40.0
  r_fi: 1500.0
  n_trajs: auto
  z0: 0.0 
  K: 0.03
  alpha: 0.6
  use_precalculated: true

integrator:
  n_iterations: 2
  save_path: "./debug"
  integrator_r_min: 6.0
  integrator_r_max: 50000.0
  integrator_z_min: 0.0
  integrator_z_max: 50000.0

numerical_tolerances:
  disk_integral_atol: 0
  disk_integral_rtol: 1e-3
  disk_integral_maxevals: 10000
  integrator_atol: 1e-8
  integrator_rtol: 1e-3
  scattering_atol: 0
  scattering_rtol: 1e-3
  
