system:
  qwind_path: /cosma7/data/dp004/dc-quer1/Qwind.jl
  n_cpus: 16
  partition: cosma7-shm
  account: dp004
  max_time: 72:00:00
  job_name: qwind
  
black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  relativistic: true 
  f_uv: auto
  f_x: 0.15
  n_r: 1000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0
  xray_opacity: boost
  tau_uv_calculation: no_tau_uv
  disk_integral_rtol: 1e-3
  wind_interpolator:
    update_grid_method: "average"
    vacuum_density: 1e2
    n_integrator_interpolation: 10000
    nz: 500 
    nr: auto 

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000.0
  z_min: 0.0
  z_max: 10000.0

initial_conditions:
  mode: CAKIC
  r_in: 16.23989458920418
  r_fi: 1500.0
  n_lines: auto
  log_spaced: true
  z_0: 0.0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.61
  use_precalculated: true

integrator:
  n_iterations: 50
  atol: 1e-8
  rtol: 1e-3
  #save_path: "/home/arnau/code/Qwind.jl/runs/tests"
  save_path: "./debugging"
