system:
  qwind_path: /cosma7/data/dp004/dc-quer1/Qwind.jl
  n_cpus: 112
  partition: cosma7-shm
  account: dp004
  max_time: 72:00:00
  job_name: qwind
  
black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  mode: QsosedRadiation # RERadiation: Risaliti & Elvis, QsosedRadiation: Done
  relativistic: true
  f_x: 0.15
  n_r: 1000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0
  xray_opacity: boost
  disk_integral_rtol: 1e-3

radiative_transfer:
  mode: RegularGrid
  interpolator: 
    type: WindInterpolator 
    vacuum_density: 1e2
    n_timesteps: 10000
    nz: 500 #500 #"@vary grid 50,100,500,1000"
    nr: 500

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000.0
  z_min: 0.0
  z_max: 10000.0

initial_conditions:
  mode: CAKIC
  r_in: 20.0
  r_fi: 1500.0
  n_lines: auto #"@vary grid 50,100,500,1000,5000,10000" #2000
  log_spaced: true
  z_0: 0.0 # Rg
  #n_0: 1e10
  #v_0: 2e6
  K: 0.03
  alpha: 0.6
  mu: 0.68

integrator:
  n_iterations: 50
  atol: 1e-8
  rtol: 1e-3
  #save_path: "/home/arnau/code/Qwind.jl/runs/tests"
  save_path: "./tests"
