system:
  n_cpus: 1
  queue: cosma
  account: durham
  max_time: 72
  job_name: qwind
  
black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  mode: QsosedRadiation # RERadiation: Risaliti & Elvis, QsosedRadiation: Done
  f_x: 0.15
  n_r: 1000

radiative_transfer:
  mode: RegularGrid
  density_interpolator: 
    type: VIGrid
    vacuum_density: 1e2
    n_timesteps: 10000
    n: "@vary grid 50,100,200,500"

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000
  z_min: 0.0
  z_max: 10000

initial_conditions:
  mode: CAKIC #UniformIC
  r_in: 50 #"@vary linear 10 200 4"
  r_fi: 1300
  n_lines: 200
  log_spaced: true
  z_0: 0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.5

integrator:
  n_iterations: 10
  atol: 1e-8
  rtol: 1e-3
  #save_path: "/home/arnau/code/Qwind.jl/runs/test_resolution"
  save_path: "/cosma7/data/dp004/dc-quer1/Qwind.jl/runs/test_resolution"
