system:
  #qwind_path: /cosma5/data/durham/covid19/arnau/qwind/Qwind.jl
  #qwind_path: /home/arnau/code/Qwind.jl
  qwind_path: /cosma7/data/dp004/dc-quer1/Qwind.jl
  n_cpus: 48
  partition: cosma7-shm2
  account: dp004
  max_time: 24:00:00
  job_name: qwind
  
black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  mode: QsosedRadiation # RERadiation: Risaliti & Elvis, QsosedRadiation: Done
  relativistic: true
  f_x: 0.15
  n_r: 1000
  z_xray: 0.0


radiative_transfer:
  mode: RegularGrid
  density_interpolator: 
    type: WindInterpolator #"@vary grid VIGrid,WindInterpolator"
    vacuum_density: 1e2
    n_timesteps: 10000
    nz: 1000 #"@vary grid 50,100,500,1000"
    nr: auto

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000.0
  z_min: 0.0
  z_max: 10000.0

initial_conditions:
  mode: CAKIC #UniformIC
  r_in: 50.0
  r_fi: 1300.0
  n_lines: auto #"@vary grid 50,100,500,1000,5000,10000" #2000
  log_spaced: true
  z_0: 0.0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.5

integrator:
  n_iterations: 50
  atol: 1e-8
  rtol: 1e-3
  #save_path: "/home/arnau/code/Qwind.jl/runs/test_resolution50"
  save_path: "/cosma7/data/dp004/dc-quer1/Qwind.jl/runs/tests_rin50_500_noaverage"
  #save_path: "/cosma5/data/durham/covid19/arnau/qwind/Qwind.jl/runs/multinode_tests_nthreads"
  #save_path: "/cosma5/data/durham/covid19/arnau/qwind/Qwind.jl/runs/big_job_changelines"
