system:
  qwind_path: /cosma/home/dp004/dc-quer1/Qwind.jl
  n_cpus: 16
  partition: cosma
  account: durham
  max_time: 72:00:00
  job_name: qwind

black_hole:
  M: "@vary grid 1e8,1e9,1e10" # take the values specified
  mdot: "@vary log 0.1 0.5 5" # from 0.1 to 0.5, 5 values log spaced
  spin: 0.0

radiation:
  relativistic: true
  f_uv: 0.85
  f_x: 0.15
  n_r: 2000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0
  uv_opacity: thomson
  xray_opacity: boost 
  xray_scattering: false
  tau_uv_calculation: no_tau_uv
  vacuum_density: 1e2
  update_grid_method: "average"
  grid_nz: 250
  grid_nr: auto
  mu_nucleon: 0.61

initial_conditions:
  mode: cak
  r_in: 20.0
  r_fi: 1500.0
  n_trajs: 50
  z0: 0.0 
  K: 0.03
  alpha: 0.6
  use_precalculated: false

integrator:
  n_iterations: 5
  save_path: "./parameter_scan_example"
  integrator_r_min: 6.0
  integrator_r_max: 10000.0
  integrator_z_min: 0.0
  integrator_z_max: 10000.0

numerical_tolerances:
  disk_integral_atol: 0
  disk_integral_rtol: 1e-3
  disk_integral_maxevals: 10000
  integrator_atol: 1e-8
  integrator_rtol: 1e-3
  scattering_atol: 0
  scattering_rtol: 1e-3
  
