system:
  qwind_path: /cosma/home/dp004/dc-quer1/Qwind.jl
  sysimage_path: /cosma/home/dp004/dc-quer1/sys_everywhere.so
  n_cpus: 16
  partition: cosma6
  account: dp004
  max_time: 72:00:00
  job_name: proga04
  
black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  relativistic: false
  f_uv: 0.9
  f_x: 0.1
  n_r: 2000
  disk_r_in: 6.0
  disk_r_out: 3000.0
  z_xray: 1.5
  disk_height: 1.5
  xray_opacity: thomson
  uv_opacity: thomson
  xray_scattering: false
  tau_uv_calculation: no_tau_uv
  fm_interp_method_flag: analytic
  vacuum_density: 1e2
  update_grid_method: "average"
  grid_nz: 250
  grid_nr: 250
  mu_nucleon: 1.0

initial_conditions:
  mode: cak
  r_in: 60.0
  r_fi: 1600.0
  n_trajs: auto
  trajs_spacing: log
  z_0: 1.5
  v_0: thermal
  K: 0.03
  alpha: 0.6
  z_disk: 1.5
  use_precalculated: false

integrator:
  n_iterations: 25
  save_path: "/cosma7/data/dp004/dc-quer1/qwind/proga2"
  integrator_r_min: 6.0
  integrator_r_max: 3000.0
  integrator_z_min: 0.0
  integrator_z_max: 3000.0

numerical_tolerances:
  disk_integral_atol: 0
  disk_integral_rtol: 5e-4
  disk_integral_maxevals: 10000
  integrator_atol: 1e-8
  integrator_rtol: 1e-3
  scattering_atol: 0
  scattering_rtol: 1e-3
  
