system:
  qwind_path: /cosma/home/dp004/dc-quer1/Qwind.jl
  #qwind_path: /cosma7/data/dp004/dc-quer1/Qwind.jl
  n_cpus: 32
  partition: cosma
  account: durham
  max_time: 72:00:00
  job_name: qwind
  
black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  mode: QsosedRadiation # RERadiation: Risaliti & Elvis, QsosedRadiation: Done
  relativistic: true
  f_x: 0.15
  n_r: 2000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0


radiative_transfer:
  mode: RegularGrid
  interpolator: 
    type: WindInterpolator #"@vary grid VIGrid,WindInterpolator"
    vacuum_density: 1e2
    n_timesteps: 10000
    nz: 500 #"@vary grid 50,100,500,1000"
    nr: auto

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000.0
  z_min: 0.0
  z_max: 10000.0

initial_conditions:
  mode: CAKIC #UniformIC
  r_in: "@vary grid 20,25,30,35,40,45,50,60,70,80,90,100,120,140"
  #r_in: 20.0
  r_fi: 1300.0
  n_lines: "auto"
  log_spaced: true
  z_0: 0.0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.5

integrator:
  n_iterations: 50
  atol: 1e-8
  rtol: 1e-3
  save_path: "/cosma6/data/dp004/dc-quer1/qwind_runs/new_coordinates_big_v_long"
  #save_path: "/home/arnau/code/Qwind.jl/rin_autok"
