system:
  qwind_path: /cosma/home/dp004/dc-quer1/Qwind.jl
  n_cpus: 32
  partition: cosma
  account: durham
  max_time: 72:00:00
  job_name: qwind
  
black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  relativistic: true
  f_uv: auto
  f_x: 0.15
  n_r: 2000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0
  xray_opacity: boost
  tau_uv_calculation: disk
  wind_interpolator:
    vacuum_density: 1e2
    n_integrator_interpolation: 10000
    nz: 500 
    nr: auto 

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000.0
  z_min: 0.0
  z_max: 10000.0

initial_conditions:
  mode: CAKIC #UniformIC
  r_in: "@vary grid 20,25,30,40,50,75,100,125,150,175,200,300,400,500"
  #r_in: "@vary grid 225,250,275"
  #r_in: "@vary grid 25,30"
  r_fi: 1500.0
  n_lines: auto
  log_spaced: true
  z_0: 0.0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.61

integrator:
  n_iterations: 50
  atol: 1e-8
  rtol: 1e-3
  save_path: "/cosma5/data/durham/covid19/arnau/qwind/rework/rin_scan"
