system:
  qwind_path: /cosma/home/dp004/dc-quer1/Qwind.jl
  sysimage_path: /cosma/home/dp004/dc-quer1/sys_everywhere.so
  n_cpus: 32
  partition: cosma6
  account: dp004
  max_time: 24:00:00
  job_name: qwind
  
black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  relativistic: true
  f_uv: auto
  f_x: 0.15
  n_r: 2000
  disk_r_in: 6.0
  z_xray: 0.0
  disk_height: 0.0
  uv_opacity: thomson
  xray_opacity: boost
  xray_scattering: false
  tau_uv_calculation: disk 
  disk_integral_rtol: 1e-3
  wind_interpolator:
    update_grid_method: "average"
    vacuum_density: 1e2
    n_integrator_interpolation: 10000
    nr: 250
    nz: 250 

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000.0
  z_min: 0.0
  z_max: 10000.0

initial_conditions:
  mode: CAKIC #UniformIC
  r_in: "@vary log 10.0 250 10"
  #r_in: 20
  r_fi: 1500.0
  n_lines: auto
  log_spaced: true
  z0: 0.0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.61
  use_precalculated: true
  interapolation_mode: interpolation


integrator:
  n_iterations: 50
  atol: 1e-8
  rtol: 1e-3
  #save_path: "/cosma5/data/durham/covid19/arnau/qwind/final/rin_scan_ref"
  save_path: "/cosma6/data/dp004/dc-quer1/qwind_runs/rin_scan_fixed_grid"
