black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  mode: QsosedRadiation # RERadiation: Risaliti & Elvis, QsosedRadiation: Done
  f_x: 0.15
  n_r: 1000

radiative_transfer:
  mode: RegularGrid
  density_interpolator: 
    type: SmoothedGrid
    vacuum_density: 1e2
    n_timesteps: 10000
    kernel_size: 10
    nr: 50
    nz: 51

grid:
  # units of Rg
  r_min: 6.0
  r_max: 10000
  z_min: 0.0
  z_max: 10000

initial_conditions:
  mode: CAKIC #UniformIC
  launch_range: [200, 1000]
  n_lines: auto #128
  log_spaced: true
  z_0: 0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.5
  n_0: 2e8 # cm^-3
  v_0: 5e7 # cm / s


integrator:
  n_iterations: 2
  atol: 1e-6
  rtol: 1e-3
  save_path: "reults_tests_kernel_10_rin50"
