black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter [0,1)

radiation:
  mode: RERadiation # RERadiation: Risaliti & Elvis, QsosedRadiation: Done
  f_uv: 0.85
  f_x: 0.15

radiative_transfer:
  mode: RERadiativeTransfer 
  shielding_density: 2e8 # cm^-3
  r_in: 100

grid:
  # units of Rg
  r_min: 0.0
  r_max: 10000
  z_min: 1.0
  z_max: 10000

initial_conditions:
  mode: UniformIC
  z_0: 1.0 # Rg
  n_0: 2e8 # cm^-3
  v_0: 5e7 # cm / s
  launch_range: [100, 2000]
  n_lines: 5
  log_spaced: false

integrator:
  n_iterations: 1
  atol: 1e-8
  rtol: 1e-3
  save_path: results



