black_hole:
  M: 1e8 # solar masses
  mdot: 0.5 # Eddington units
  spin: 0.0 # spin parameter (-1,1)

radiation:
  mode: QsosedRadiation # RERadiation: Risaliti & Elvis, QsosedRadiation: Done
  f_x: 0.15
  n_r: 100

radiative_transfer:
  mode: AdaptiveMesh
  vacuum_density: 1e2
  atol: 1e-2
  rtol: 1e-2
  cell_min_size: 1e-6
  n_timesteps: 10000

grid:
  # units of Rg
  r_min: 0.0
  r_max: 10000
  z_min: 0.0
  z_max: 10000

initial_conditions:
  mode: CAKIC
  launch_range: [6, 2000]
  n_lines: 120
  log_spaced: true
  z_0: 0 # Rg
  K: 0.03
  alpha: 0.6
  mu: 0.5
  n_0: 2e8 # cm^-3
  v_0: 5e7 # cm / s


  #initial_conditions:
  #  mode: CAKIC 
  #  launch_range: [6, 2000]
  #  n_lines: 60
  #  log_spaced: true
  #  z_0: 1.0 # Rg
  #  K: 0.03
  #  alpha: 0.6
  #  mu: 0.5
  #  #n_0: 2e8 # cm^-3
  #  #v_0: 5e7 # cm / s

integrator:
  n_iterations: 10
  atol: 1e-6
  rtol: 1e-3
  save_path: results
